CREATE TABLE STUDENT(
student_id INT PRIMARY KEY NOT NULL,
student_name VARCHAR(30) NOT NULL,
student_marks INT NOT NULL
);
show databases;
SELECT * FROM STUDENT;
INSERT INTO STUDENT VALUES 
(101,"SWAPNA",92),(102,"SWATHI",59),(103,"SWETHA",88),
(104,"SPANDANA",99),(105,"YAMUNA",86),(161,"PREETHI",93),
(107,"SNEHA",86),(108,"VASAVI",75),(110,"ARUNA",55),
(109,"SUMANTH",50);
SELECT * FROM STUDENT WHERE student_marks=93;
SELECT * FROM STUDENT WHERE student_marks<74;
SELECT * FROM STUDENT WHERE student_marks<=93;
SELECT * FROM STUDENT WHERE student_marks>93;
SELECT * FROM STUDENT WHERE student_marks>=93;
SELECT * FROM STUDENT WHERE student_marks<>93;
SELECT * FROM STUDENT WHERE student_marks BETWEEN 40 AND 99;
SELECT * FROM STUDENT WHERE student_marks BETWEEN 70 AND 99;
-- ASC IS DEFAULT
SELECT * FROM STUDENT WHERE student_marks BETWEEN 70 AND 99 ORDER BY student_marks;
SELECT * FROM STUDENT WHERE student_marks BETWEEN 40 AND 99 ORDER BY student_marks ASC; 
-- DEC IS MANUALLY WRITTEN BY USER 
SELECT * FROM STUDENT WHERE student_marks BETWEEN 40 AND 99 ORDER BY student_marks DESC; 
SELECT * FROM STUDENT WHERE NOT student_marks = 93;
-- FIND UNIQUE ADDRESS
SELECT DISTINCT student_address FROM RGMCET;
SELECT COUNT(DISTINCT student_address) FROM RGMCET;
SELECT * FROM RGMCET LIMIT 3;
SELECT *FROM RGMCET WHERE student_address = 'NANDYAL' LIMIT 2;
SELECT *FROM RGMCET ORDER BY student_address = 'NANDYAL' LIMIT 2 ;
SELECT count(student_address),student_address FROM RGMCET GROUP BY student_address;
SELECT * FROM RGMCET;
SELECT *FROM RGMCET WHERE student_clg="RGM" ORDER BY student_session LIMIT 2;

CREATE TABLE DOB(
DAT_E DATE NOT NULL);
INSERT INTO DOB VALUES ('2003-07-20');
SELECT * FROM DOB;

